version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}sombrasoftmovierentalapi
    container_name: api
    ports:
      - 5000:80
    build:
      context: .
      dockerfile: ./SombraSoft.MovieRental.API/Dockerfile
    links:
      - mongo
    networks:
      - container-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: sombra
      ME_CONFIG_BASICAUTH_PASSWORD: sombra123!
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: MongoDB2020!
    links:
      - mongo
    networks:
      - container-network

  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2020!
    ports:
      - 27017:27017
    networks:
      - container-network

  web:
    image: ${DOCKER_REGISTRY-}sombrasoftmovierentalweb
    container_name: web
    ports:
      - 8080:80
    build:
      context: ./SombraSoft.MovieRental.Web
      dockerfile: Dockerfile

networks: 
    container-network:
      driver: bridge